var app =angular.module('QueryApp',['ngRoute', 'ngCookies']);
    app.config(function($routeProvider){
        $routeProvider
        .when('/',{
        	templateUrl:"pages/query.html",
        	controller:"QueryController"
        })
        .when('/dataBase',{
        	templateUrl:"pages/dataBase.html",
        	controller:"DataBaseController"
        })
        .when('/dashboard',{
        	templateUrl:"pages/dashboard.html",
        	controller:"DashboardController"
        })
         .when('/day',{
        	templateUrl:"pages/day.html",
        	controller:"DayController"
        })
        .otherwise({redirectTo:'/'});
    });